spring.application.name=ms-edututor-bff
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://a8235d1f-255d-4c0c-8a1c-eed1b072689c.ciamlogin.com/a8235d1f-255d-4c0c-8a1c-eed1b072689c/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=2f150108-cdc6-4386-82cf-f1b957ff99fb

# Base URL de los microservicios de dominio (sessions, catalog, etc.).
# Placeholder hasta que existan esos servicios.
edututor.domain-services.base-url=http://localhost:9000
